### ISSUE TITLE
支持一波

### ISSUE THREAD

**Issue by beyonder996** [ppchart/ppchart#1]
本来看到是2.15停服，想着年后用无头浏览器抓一下数据自己存一份，没想到大佬这么快站点都出来了，点赞，持续关注

**Comment by ppchart** [comment]
> 本来看到是2.15停服，想着年后用无头浏览器抓一下数据自己存一份，没想到大佬这么快站点都出来了，点赞，持续关注

感谢支持！虎年大吉！

目前还有许多图表虽然数据有但运行不起来，持续订正中
