### ISSUE TITLE
目前最大的问题就是很多图片和json文件没有爬下来，希望能尽快解决。加油！

### ISSUE THREAD

**Issue by sunriquelme** [ppchart/ppchart#2]

**Comment by ppchart** [comment]
你好，可以留下 json 文件名称，帮你查找一下，静态资源我这里应该是全的都有

**Comment by sunriquelme** [comment]
> 你好，可以留下 json 文件名称，帮你查找一下，静态资源我这里应该是全的都有

data-1522745440620-rktPlpgjz.json

**Comment by sunriquelme** [comment]
现在看http://asset.ppchart.com/下图片是可以访问的，但是json404，还没有把json文件放到服务器下吗？

**Comment by ppchart** [comment]
> 现在看[http://asset.ppchart.com/下图片是可以访问的，但是json404，还没有把json文件放到服务器下吗？](http://asset.ppchart.com/%E4%B8%8B%E5%9B%BE%E7%89%87%E6%98%AF%E5%8F%AF%E4%BB%A5%E8%AE%BF%E9%97%AE%E7%9A%84%EF%BC%8C%E4%BD%86%E6%98%AFjson404%EF%BC%8C%E8%BF%98%E6%B2%A1%E6%9C%89%E6%8A%8Ajson%E6%96%87%E4%BB%B6%E6%94%BE%E5%88%B0%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B8%8B%E5%90%97%EF%BC%9F)

权限有点问题，先放开解决了
