### ISSUE TITLE
Uncaught ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by q479360791** [ppchart/ppchart#3]
Uncaught ReferenceError: globalThis is not defined
QQ浏览器(10.8.5)报错, 白屏
谷歌浏览器可以正常访问

**Comment by ppchart** [comment]
> 

推荐使用 Chrome 和 Edge，其它浏览器兼容会尽快处理。

感谢 @q479360791 亲的反馈！鸽儿喽～奈斯～
