### ISSUE TITLE
echart 版本切换

### ISSUE THREAD

**Issue by Jaydar** [ppchart/ppchart#6]
有很多demo 是低版本的  导致打开后无现实

**Comment by ppchart** [comment]
> 有很多demo 是低版本的 导致打开后无现实

### 问题说明
- 运行无显示是因为代码内部存在侵入式代码诸如：使用了 JQ 的 $ 等原因
- chart 详情页内部会加载代码数据指定的 echart 版本

### 后续规划
- 【Ing 正在做的事】中规划了兼容更多数据正常显示
- 针对该 Issue Title，感谢反馈，已将 echart 版本切换划分至【Feature】

**Comment by ppchart** [comment]
已支持
