### ISSUE TITLE
http://ppchart.com/#/detail/xrJDKzwZQ 报错

### ISSUE THREAD

**Issue by imingdev** [ppchart/ppchart#7]
http://ppchart.com/#/detail/xrJDKzwZQ 报错
缺少 https://cdn.bootcss.com/PapaParse/4.1.2/papaparse.min.js 库

**Comment by ppchart** [comment]
> http://ppchart.com/#/detail/xrJDKzwZQ 报错 缺少 https://cdn.bootcss.com/PapaParse/4.1.2/papaparse.min.js 库

ReferenceError: $ is not defined
该案例引用了外部依赖，暂无法进行实时调试
此类数据将在后续迭代后再支持

**Comment by Bclound** [comment]
@ppchart 给你提供个技术支持，如果你有用new Function, 可以把$作为参数传进去，这样代码编辑那块就可以用jquery语法了。
![image](https://user-images.githubusercontent.com/57136514/154010802-20c29b13-fc11-4195-87cd-c60675c27c9d.png)

**Comment by imingdev** [comment]
@ppchart 可以使用这种模式也可以，如果传入参数就用参数的，没有传入就走全局的
```
const getOption = (src, obj) => {
    const name = 'sandboxName';

    try {
        new Function(name, `with(${name}){${src}}`)(obj);
    } catch (e) {
    }

    return obj?.option || null;
};

const option = getOption(optionCode,{
 $,
 option:{}
})
```

**Comment by ppchart** [comment]
> @ppchart 给你提供个技术支持，如果你有用new Function, 可以把$作为参数传进去，这样代码编辑那块就可以用jquery语法了。 ![image](https://user-images.githubusercontent.com/57136514/154010802-20c29b13-fc11-4195-87cd-c60675c27c9d.png)

稳

**Comment by ppchart** [comment]
> @ppchart 可以使用这种模式也可以，如果传入参数就用参数的，没有传入就走全局的
> 
> ```
> const getOption = (src, obj) => {
>     const name = 'sandboxName';
> 
>     try {
>         new Function(name, `with(${name}){${src}}`)(obj);
>     } catch (e) {
>     }
> 
>     return obj?.option || null;
> };
> 
> const option = getOption(optionCode,{
>  $,
>  option:{}
> })
> ```

赞

**Comment by ppchart** [comment]
1. 目前支持了 $ 的使用，但外部脚本没有加载，所以代码仍不能运行成功，待增加外部依赖加载即可
2. 还存在部分数据依赖的 Echarts 版本不对，因此待增加 Echarts 版本切换即可

上述两个问题在本周内会支持&解决
@imingdev
