### ISSUE TITLE
无法注册，手机号登陆收不到验证码

### ISSUE THREAD

**Issue by anzhihe** [ppchart/ppchart#8]
大佬，目前无法注册，手机号登陆也收不到验证码。
tip：网站做图很方便，感谢大佬。提个小建议，chart实例打开目前是弹窗，后边能不能用单独的uri路径，一不小心按了esc键，数据没保存白调了，难受😂

**Comment by ppchart** [comment]
目前腾讯将接入的身份认证系统口子关闭维护了
chart 实例可以单击卡片右上角的 Icon 新打开标签页进行访问哦

> 大佬，目前无法注册，手机号登陆也收不到验证码。 tip：网站做图很方便，感谢大佬。提个小建议，chart实例打开目前是弹窗，后边能不能用单独的uri路径，一不小心按了esc键，数据没保存白调了，难受😂

**Comment by anzhihe** [comment]
好的，多谢多谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月26日(周二) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ppchart/ppchart] 无法注册，手机号登陆收不到验证码 (Issue #8)




 
目前腾讯将接入的身份认证系统口子关闭维护了
 chart 实例可以单击卡片右上角的 Icon 新打开标签页进行访问哦
  
大佬，目前无法注册，手机号登陆也收不到验证码。 tip：网站做图很方便，感谢大佬。提个小建议，chart实例打开目前是弹窗，后边能不能用单独的uri路径，一不小心按了esc键，数据没保存白调了，难受😂
